# YOLOv11n-seg Training Configuration

# Model parameters
model: yolo11n-seg.pt
epochs: 100
imgsz: 640
batch: 4
workers: 4
device: 0  # Use GPU device 0, use 'cpu' for CPU only

# Dataset
data: ./dataset/data.yaml

# Output
name: yolov11n_seg_custom_model
project: runs/segment