# YOLOv11n Training Configuration

# Model parameters
model: yolov11n.pt
epochs: 100
imgsz: 640
batch: 4
workers: 4
device: 0  # Use GPU device 0, use 'cpu' for CPU only

# Dataset
data: dataset/data.yaml

# Output
name: yolov11n_custom_model
project: runs/detect